# Generated by Django 2.2.14 on 2021-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('OW', 'Out Wear'), ('SW', 'Sports Wear')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('d', ' danger')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
